apiVersion: apps/v1
kind: Deployment
metadata:
  name: flight-reservation-backend
  namespace: flight-reservation
  labels:
    app: flight-reservation-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flight-reservation-app
  template:
    metadata:
      labels:
        app: flight-reservation-app
    spec:
      containers:
      - name: flight-reservation-app
        image: abhipraydh96/fly-back
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
